# Generated by Django 5.2.1 on 2025-09-07 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SourceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfIncident', models.TextField()),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.cyberattack')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.sourceincident')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.statusincidents')),
            ],
        ),
    ]
