# Generated by Django 5.2.1 on 2025-09-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberattack',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
