# Generated by Django 5.2 on 2025-04-21 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)])),
                ('password', models.TextField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
